### ISSUE TITLE
Often something happens to meshes, their vertices spontaneously riped.

### ISSUE THREAD

**Issue by MarkMironov** [umiyuki/Artstage-Issues#67]
I completely normalize the mesh for the subsurf, but after a while I find that some vertices are riped. And so constantly. This is clearly visible if the subsurf is constantly on.
![Image 2019, 10, 18, 19, 31, 25](https://user-images.githubusercontent.com/55280047/67113683-c74b1400-f1e2-11e9-8b3c-0024894067ff.png)

**Comment by MarkMironov** [comment]
This happens when you use the Create Face tool. When you create a polygon in a mesh, the geometry seems to be recalculated, and then there are changes in which the vertices may riped.

**Comment by umiyuki** [comment]
I want to tackle this problem, but I'm afraid I couldn't figure out exactly what was happening with your images and comments alone.
If you can send us an asm file that reproduces the problem, it will help.
https://www.dropbox.com/request/HOU04JVUNXAlPxqmOMUu

**Comment by MarkMironov** [comment]
@umiyuki 

https://youtu.be/Kn6y5kjCYDw

A very revealing file in which two bugs can be detected at once. Please pay particular attention to these two bugs. These are the most repetitive, and interfering with the work that I could detect.

1. Initially, this mesh did not have holes, but one appeared spontaneously in the modeling process. In the video I show how she spontaneously disappears.
When the mesh is large, there can be dozens of such bugs. You make a beautiful, smoothed model, and then you discover that it has holes and the wrong "weights."

2. At the end of the video, a bug with triangles appears again.

If you do everything as in the video, then you will catch both bugs.
File sent to Dropbox. Called "The mesh changes itself + triangle faces bug".

**Comment by umiyuki** [comment]
Thank you for sending the file!
I opened the file and checked it. I thought this might not be a bug.
In fact, there was a gap in the model mesh. If these vertices were collapsed, the problem should not have occurred. You can check the gap by zooming a lot in on the model.
![イラスト](https://user-images.githubusercontent.com/6958622/67359369-03dd8d80-f59e-11e9-8b29-371a91a7c818.jpg)

Second, this model is very huge. In general, the larger the vertex position scale, the greater the error. It is appropriate that the model scale fits in the grid display. (It's OK that scale on the display may be enlarged or reduced)
When creating a face with "Create face tool", the process of merging the existing object and the created face is performed, and the vertices at the same position are merged. If the model is huge, the possibility of merging wrong vertices increases. This is the reason why gaps appear or disappear in the model.
I haven't noticed this problem before, but I think it's better to put a notice somewhere rather than fix the program.

Also, the triangle bug that occurred at the end of the video has been fixed locally.

**Comment by MarkMironov** [comment]
@umiyuki Thank you!
Holes spontaneously appeared, despite the fact that I merged the vertices through the "collapse vertices".
I had another mesh (large scaled) where this happened all the time. I collapse vertices and after a while I discovered that a problem appeared in the same place.
But maybe this is due to the scale of the model.. I don’t know. I will need to try again on a normal scale.

But here is another case:
https://youtu.be/ZMN74kiuQrM
If we apply subsurf to the cube that loads when the program starts, we will see that it is not completely subdivided. Where the edges were, seams are visible.  Could it be UV seams? In any case, should they be visible when subdiv applied? I didn’t assign any weights to the edges, which means the mesh should be completely smoothed.
And why do the seams disappear with the collapse of the peaks? Are there double vertices there? No. But why does vertex collapse improve the appearance of the object?

**Comment by MarkMironov** [comment]
@umiyuki 
After the update, there is still a bug similar to the one with triangular faces. 
https://youtu.be/gdGY0cwPKok
This is the area on the ear.

File sent to Dropbox. Called "model freezes".

**Comment by umiyuki** [comment]
After updating once with Steam(I was thought the update would not be notified until after posting the announcement.) I noticed that there was still a problem during the test, made additional corrections and updated again.  It should have been fixed in the second update.

**Comment by umiyuki** [comment]
If there is no progress in the next two months, close this issue.
